"""
    Tipos de dados
    str=string "Textos"
    int=inteiro 123456 negatifvo ou positivo, sem o ponto.
    float= real/ponto flutuante 10.50 1.5 -1.5
    bool= booleano/lógico  - True/False 10==10
"""
#String = nome
print("Joaquim!", type("Joaquim"))

#Int= inteiro(idade)
print(2, type(2))

#Float= valor real/ altura
print(1.76, type(1.76))

#bool= lógico, verdadeiro ou falso/True ou False
print(2<18, type(2<18))